name: Tests Pipeline

on:
  pull_request:
    branches: [ main ]

  schedule:
    - cron: '0 6 * * *'

  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser to run UI tests'
        required: true
        default: 'Chrome'
        type: choice
        options:
          - Chrome
          - Edge

jobs:

  api-tests:
    name: Run API Tests
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - run: dotnet restore
      - run: dotnet build --no-restore --configuration Release

      - name: Run API Tests
        run: dotnet test --filter "Category=API" --no-build --configuration Release --logger "trx;LogFileName=api-test-results.trx"
        continue-on-error: true

      - name: Upload API Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-test-results
          path: "**/*.trx"


  ui-tests:
    name: Run UI Tests (Linux)
    runs-on: ubuntu-latest
    needs: api-tests
    if: always()

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - run: dotnet restore
      - run: dotnet build --no-restore --configuration Release

      # Install Chrome on Linux
      - name: Install Chrome
        if: ${{ github.event.inputs.browser == 'Chrome' || github.event_name != 'workflow_dispatch' }}
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable

      # Install Edge on Linux
      - name: Install Edge
        if: ${{ github.event.inputs.browser == 'Edge' }}
        run: |
          sudo apt update
          sudo apt install -y microsoft-edge-stable

      - name: Set Browser Variable
        run: echo "BROWSER=${{ github.event.inputs.browser || 'Chrome' }}" >> $GITHUB_ENV

      - name: Run UI Tests
        run: dotnet test --filter "Category=UI" --no-build --configuration Release --logger "trx;LogFileName=ui-test-results.trx"
        timeout-minutes: 30


  publish-ui-artifacts:
    name: Publish UI Results & Screenshots
    runs-on: ubuntu-latest
    needs: ui-tests
    if: always()

    steps:
      - uses: actions/checkout@v4

      - name: Upload UI Test Results & Screenshots
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-results-${{ github.event.inputs.browser || 'Chrome' }}
          path: |
             **/bin/Release/net10.0/Screenshots/**/*.png
          if-no-files-found: warn
          retention-days: 30
