name: Tests Pipeline

on:
  pull_request:
    branches: [ main ]

  schedule:
    - cron: '0 6 * * *'

  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser to run UI tests'
        required: true
        default: 'Chrome'
        type: choice
        options:
          - Chrome
          - Edge

jobs:

  api-tests:
    name: Run API Tests
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Run API Tests
        run: dotnet test --filter "Category=API" --no-build --configuration Release --logger "trx;LogFileName=api-test-results.trx"
        continue-on-error: true

      - name: Upload API Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-test-results
          path: |
            **/*.trx
          retention-days: 30


  ui-tests:
    name: Run UI Tests
    runs-on: windows-latest
    needs: api-tests
    if: always()

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Install Chrome
        if: ${{ github.event.inputs.browser == 'Chrome' || github.event_name != 'workflow_dispatch' }}
        run: choco install googlechrome selenium-chrome-driver -y --no-progress --ignore-checksums

      - name: Install Edge Driver
        if: ${{ github.event.inputs.browser == 'Edge' }}
        run: choco install selenium-edge-driver -y --no-progress --ignore-checksums

      - name: Set Browser Environment Variable
        run: echo "BROWSER=${{ github.event.inputs.browser || 'Chrome' }}" >> $GITHUB_ENV

      - name: Run UI Tests
        run: dotnet test --filter "Category=UI" --no-build --configuration Release --logger "trx;LogFileName=ui-test-results.trx"
        timeout-minutes: 30
        continue-on-error: true

      - name: Upload UI Test Results & Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-results-${{ github.event.inputs.browser || 'Chrome' }}
          path: |
            **/*.trx
            **/Screenshots/**/*.png
          retention-days: 30
