name: Tests Pipeline

on:
  pull_request:
    branches: [ main ]

  schedule:
    - cron: '0 6 * * *'

  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser to run UI tests'
        required: true
        default: 'Chrome'
        type: choice
        options:
          - Chrome
          - Edge

jobs:

  api-tests:
    name: Run API Tests
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - run: dotnet restore
      - run: dotnet build --no-restore --configuration Release

      - name: Run API Tests
        run: dotnet test --filter "Category=API" --no-build --configuration Release --logger "trx;LogFileName=api-test-results.trx"
        continue-on-error: true

      - name: Upload API Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-test-results
          path: "**/*.trx"


  ui-tests:
    name: Run UI Tests
    runs-on: windows-latest
    needs: api-tests
    if: always()
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      
      - run: dotnet restore
      - run: dotnet build --no-restore --configuration Release
      
      - name: Set Browser Variable
        run: echo "BROWSER=${{ github.event.inputs.browser || 'Chrome' }}" >> $GITHUB_ENV

      - name: Run UI Tests
        run: dotnet test --filter "Category=UI" --no-build --configuration Release --logger "trx;LogFileName=ui-test-results.trx"
        timeout-minutes: 30

      # Upload directly from the runner where tests actually executed
      - name: Upload UI Results & Screenshots
        if: always() # Ensure screenshots upload even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-results-${{ github.event.inputs.browser }}
          # Using a relative path from the repo root is safer
          path: |
            **/ui-test-results.trx
            **/bin/Release/net10.0/Screenshots/*.png
          if-no-files-found: warn
